### ISSUE TITLE
Getting some errors when starting colab.

### ISSUE THREAD

**Issue by gilroff** [idinkov/sd-deepface-1111#10]
Getting these errors when colab is starting:

You are not currently on a branch.
Please specify which branch you want to merge with.
See git-pull(1) for details.

    git pull <remote> <branch>

Couldn't perform 'git pull' on repository in '/content/sdw/extensions/sd-deepface-1111/repo/dflive':

Another error:

*** Error loading script: ddetailerutils.py
    Traceback (most recent call last):
      File "/content/sdw/modules/scripts.py", line 295, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "/content/sdw/modules/script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "/content/sdw/extensions/sd-deepface-1111/scripts/ddetailerutils.py", line 78, in <module>
        import mmcv
    ModuleNotFoundError: No module named 'mmcv'

---
*** Error loading script: deepfacelive.py
    Traceback (most recent call last):
      File "/content/sdw/modules/scripts.py", line 295, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "/content/sdw/modules/script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "/content/sdw/extensions/sd-deepface-1111/scripts/deepfacelive.py", line 24, in <module>
        from scripts.ddetailerutils import DetectionDetailerScript, preload_ddetailer_model
      File "/content/sdw/extensions/sd-deepface-1111/scripts/ddetailerutils.py", line 78, in <module>
        import mmcv
    ModuleNotFoundError: No module named 'mmcv'

---
I'm using free colab on Tesla T4 gpu.
Btw thanks for implementing this extension.

**Comment by idinkov** [comment]
This shall be fixed with the latest commit.
