### ISSUE TITLE
ModuleNotFoundError: No Module named 'mmcv'

### ISSUE THREAD

**Issue by demasakbar** [idinkov/sd-deepface-1111#6]
I have installed mmcv in the following way

```
pip install openmim
mim install mmcv
```
But when I tried to run Automatic1111, The extension won't run because there was the following error message:

```
ModuleNotFoundError: No Module named 'mmcv'
```

How do you fix this?

Os : Windows 11
Python : v3.10.9

Detail Error
```
Error loading script: ddetailerutils.py
Traceback (most recent call last):
  File "D:\Path\StableDiff\stable-diffusion-webui\modules\scripts.py", line 256, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "D:\Path\StableDiff\stable-diffusion-webui\modules\script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\Path\StableDiff\stable-diffusion-webui\extensions\sd-deepface-1111\scripts\ddetailerutils.py", line 78, in <module>
    import mmcv
ModuleNotFoundError: No module named 'mmcv'


Error loading script: deepfacelive.py
Traceback (most recent call last):
  File "D:\Path\StableDiff\stable-diffusion-webui\modules\scripts.py", line 256, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "D:\Path\StableDiff\stable-diffusion-webui\modules\script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\Path\StableDiff\stable-diffusion-webui\extensions\sd-deepface-1111\scripts\deepfacelive.py", line 24, in <module>
    from scripts.ddetailerutils import DetectionDetailerScript, preload_ddetailer_model
  File "D:\Path\StableDiff\stable-diffusion-webui\extensions\sd-deepface-1111\scripts\ddetailerutils.py", line 78, in <module>
    import mmcv
ModuleNotFoundError: No module named 'mmcv'
```

**Comment by idinkov** [comment]
Can you try running the following:
python -m pip install -U openmim==0.3.7
python -m mim install mmcv-full==1.7.1
python -m pip install mmdet==2.28.2

This usually will execute on launch if you dont have any but probably you have a different versions.

**Comment by demasakbar** [comment]
> Can you try running the following:
> python -m pip install -U openmim==0.3.7
> python -m mim install mmcv-full==1.7.1
> python -m pip install mmdet==2.28.2
> 
> This usually will execute on launch if you dont have any but probably you have a different versions.

I tried but it still doesn't work.

**Comment by demasakbar** [comment]
```
Error loading script: ddetailerutils.py
Traceback (most recent call last):
  File "D:\Path\StableDiff\stable-diffusion-webui\modules\scripts.py", line 256, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "D:\Path\StableDiff\stable-diffusion-webui\modules\script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\Path\StableDiff\stable-diffusion-webui\extensions\sd-deepface-1111\scripts\ddetailerutils.py", line 78, in <module>
    import mmcv
ModuleNotFoundError: No module named 'mmcv'


Error loading script: deepfacelive.py
Traceback (most recent call last):
  File "D:\Path\StableDiff\stable-diffusion-webui\modules\scripts.py", line 256, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "D:\Path\StableDiff\stable-diffusion-webui\modules\script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\Path\StableDiff\stable-diffusion-webui\extensions\sd-deepface-1111\scripts\deepfacelive.py", line 24, in <module>
    from scripts.ddetailerutils import DetectionDetailerScript, preload_ddetailer_model
  File "D:\Path\StableDiff\stable-diffusion-webui\extensions\sd-deepface-1111\scripts\ddetailerutils.py", line 78, in <module>
    import mmcv
ModuleNotFoundError: No module named 'mmcv'
```

**Comment by idinkov** [comment]
I see, probably python -m mim install mmcv-full==1.7.1 gave you some output with error at the end, can you run it and give me the output. Thanks!

**Comment by idinkov** [comment]
I have just created a discord server if you want you can join it and try to debug there: https://discord.gg/3YH8jENW

**Comment by demasakbar** [comment]
> I see, probably python -m mim install mmcv-full==1.7.1 gave you some output with error at the end, can you run it and give me the output. Thanks!

```
Looking in links: https://download.openmmlab.com/mmcv/dist/cu118/torch2.0.0/index.html
Collecting mmcv-full==1.7.1
  Using cached mmcv_full-1.7.1-py2.py3-none-any.whl
Requirement already satisfied: addict in c:\users\xxxxxxx\appdata\local\programs\python\python310\lib\site-packages (from mmcv-full==1.7.1) (2.4.0)
Requirement already satisfied: numpy in c:\users\xxxxxxx\appdata\local\programs\python\python310\lib\site-packages (from mmcv-full==1.7.1) (1.24.1)
Requirement already satisfied: packaging in c:\users\xxxxxxx\appdata\local\programs\python\python310\lib\site-packages (from mmcv-full==1.7.1) (23.1)
Requirement already satisfied: Pillow in c:\users\xxxxxxx\appdata\local\programs\python\python310\lib\site-packages (from mmcv-full==1.7.1) (9.3.0)
Requirement already satisfied: pyyaml in c:\users\xxxxxxx\appdata\local\programs\python\python310\lib\site-packages (from mmcv-full==1.7.1) (6.0)
Requirement already satisfied: yapf in c:\users\xxxxxxx\appdata\local\programs\python\python310\lib\site-packages (from mmcv-full==1.7.1) (0.33.0)
Requirement already satisfied: opencv-python>=3 in c:\users\xxxxxxx\appdata\local\programs\python\python310\lib\site-packages (from mmcv-full==1.7.1) (4.7.0.72)
Requirement already satisfied: regex in c:\users\xxxxxxx\appdata\local\programs\python\python310\lib\site-packages (from mmcv-full==1.7.1) (2023.5.5)
Requirement already satisfied: tomli>=2.0.1 in c:\users\xxxxxxx\appdata\local\programs\python\python310\lib\site-packages (from yapf->mmcv-full==1.7.1) (2.0.1)
Installing collected packages: mmcv-full
Successfully installed mmcv-full-1.7.1
```

**Comment by idinkov** [comment]
Everything looks fine according to this. I will have some free time in the weekend, and we can look this in the discord, i think you are already there, right :)

**Comment by demasakbar** [comment]
> Everything looks fine according to this. I will have some free time in the weekend, and we can look this in the discord, i think you are already there, right :)

Oke. I have join on the discord

**Comment by isu-shrestha** [comment]
Has this been resolved? I am having the same problem.

**Comment by thezveroboy** [comment]
i've got the same. i'll be glad if someone tell me how to resolve it

**Comment by idinkov** [comment]
This shall be fixed with the latest commit.
