### ISSUE TITLE
No module named 'mmdet.core'

### ISSUE THREAD

**Issue by wzgrx** [idinkov/sd-deepface-1111#8]
*** Error loading script: deepfacelive.py
    Traceback (most recent call last):
      File "G:\stable-diffusion-webui\modules\scripts.py", line 295, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "G:\stable-diffusion-webui\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "G:\stable-diffusion-webui\extensions\sd-deepface-1111\scripts\deepfacelive.py", line 24, in <module>
        from scripts.ddetailerutils import DetectionDetailerScript, preload_ddetailer_model
      File "G:\stable-diffusion-webui\extensions\sd-deepface-1111\scripts\ddetailerutils.py", line 79, in <module>
        from mmdet.core import get_classes
    ModuleNotFoundError: No module named 'mmdet.core'
提示：Python 运行时抛出了一个异常。请检查疑难解答页面。

**Comment by idinkov** [comment]
Can you try running the following:
python -m pip install -U openmim==0.3.7
python -m mim install mmcv-full==1.7.1
python -m pip install mmdet==2.28.2
